//var userName = 'Timmy "The Skinny" Turner';
//you would just take everything in the html and put it in these variables
var homeContent = "<div id ='app'><div class ='home'><table class='elements'> <th colspan='2'>Pro-Bending</th> <tr> <td class='elements'> <a id = 'cups' href='#'> <img src='images/Cups.png' alt='Cups Over Flowing with Cool Water' style='width: 200px; height: 200px;'> <br> <strong>Cups</strong> </a> </td> <td class='elements'> <a id = 'pentacles' href='#'> <img src='images/Pentacles.png' alt='Inpenetrable Stone Vaults Filled with Golden Pentacles' style='width: 200px; height: 200px;'> <br> <strong>Pentacles</strong> </a> </td> </tr> <tr> <td class='elements'>  <a id = 'wands' href='#'> <img src='images/Wands.png' alt='Wind Swept Fields with Blade like Grass' style='width: 200px; height: 200px;'>  <br>  <strong>Swords</strong>   </a> </td>    <td class='elements'>        <a id = 'swords' href='#'>            <img src='images/Swords.png' alt='Charred Forest With a Great Heat Emintating from the Center' style='width: 200px; height: 200px;'>              <br>                   <strong>Wands</strong>           </a>       </td>   </tr></table></div></div>";
var aboutContent = "<h1>ABOUT</h1><p>this is a page</p>";
var productsContent = "<h1>PRODUCTS</h1><p>this is a page</p>";
var gamesContent = "<h1>PRODUCTS</h1><p>this is a page</p>";
var contactContent = "<h1>CONTACT</h1><p>this is a page</p>";

var cupsContent = '<section id = "app"><div class = "cups"><table class="elements"> <th colspan="2">Pro-Bending</th> <tr> <td class="elem-describe" rowspan="3"> <div> <p> Water benders can be found where the drinks flow. Where jubilation and elation color the air. Water benders are drawn to the excitement the reverly, the sheer jot that emanates from bars on the eve of a great night. Water is the element of change. The element of cups changing hands. The ale spilling onto the floor to be swept away by the stomping and sliding feet of people losing themselves to the rythm playing overhead. The element of eyes catching across the room and hands joining in celebration as the heat and steam from the pulsing bodies spills out onto the street, the scent of rejuvination and hydration luring in wanderers. <br>Patrons were so caught up in their euphoria they didn&#x27t notice when the drinks stopped needing cups to flow. The triumphant shouts echoed off the walls and collected in the water. The water became jubilant. The water became exalted. The water got caught in the exaltation and danced along with the patrons. And so the apatrons became one with the water. </p> </div> </td> <td class="elem-describe" style="height: 50px;"> <div class="title"> <h1>Notable Drinkers</h1> <ul><li>Mosukka</li> <li>Achak</li> </ul> </div> </td> </tr> <tr> <td class="elem-describe" rowspan="2"><div class="elem-describe"> <h1>Element Mutations</h1> <ul> <li>Adipisicing deserunt eum!</li> <li>Lorem, ipsum dolor sit amet consectetur adipisicing elit.</li> <li>Unde pariatur facere dignissimos aut soluta mollitia eveniet eligendi dolores praesentium voluptates ullam veniam reprehenderit, doloribus recusandae accusamus!</li> <li>Lorem ipsum dolor sit amet consectetur adipisicing elit. Est ex libero harum fuga!</li> <li>Ducimus odit laboriosam quia, molestiae blanditiis adipisci repellendus velit quasi ullam et? </li> </ul> </div> </td> </tr></table></div></section>';
var pentaclesContent ='<div id="app"> <div class="pentacles"> <table class="elements"> <th colspan="2">Pro-Bending</th> <tr> <td class="elem-describe" rowspan="3"> <div> <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae vero molestiae dolor praesentium facilis quibusdam repellendus consectetur excepturi maxime, minus, quam, suscipit distinctio atque delectus magnam eveniet est quas fugit! <br> Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sapiente nihil mollitia asperiores voluptas voluptatum sequi magnam, sint tempore saepe dolore earum ut cum aliquid reprehenderit et possimus repellendus laudantium hic. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi officiis ipsa facere nobis veritatis esse quos nam neque, tempora, sit culpa aperiam nihil quisquam repudiandae corrupti expedita voluptatem. Porro, consequatur. <br> Nulla quia obcaecati modi maiores earum nam quos nobis? Suscipit quas nesciunt illo praesentium adipisci libero doloremque delectus excepturi optio corrupti non sint porro alias ducimus, at fugiat quidem? Possimus. <br>Odit suscipit sint esse nam laboriosam ex quis laborum nihil aliquam doloribus similique sequi consectetur, doloremque reprehenderit minima placeat nulla nesciunt velit! Alias excepturi similique iure hic beatae repellat architecto.</p> </div> </td> <td class="elem-describe" style="height: 50px;"> <div class="title"> <!-- Chinese --> <h1>Big Bankers</h1> <ul> <li>Changying</li> <li>Dingxiang</li><li>Ulon</li> </ul> </div> </td> </tr> <tr> <td class="elem-describe" rowspan="2"> <div class="elem-describe"> <h1>Element Mutations</h1> <ul> <li>Adipisicing deserunt eum!</li> <li>Lorem, ipsum dolor sit amet consectetur adipisicing elit.</li> <li>Unde pariatur facere dignissimos aut soluta mollitia eveniet eligendi dolores praesentium voluptates ullam veniam reprehenderit, doloribus recusandae accusamus!</li> <li>Lorem ipsum dolor sit amet consectetur adipisicing elit. Est ex libero harum fuga!</li> <li>Ducimus odit laboriosam quia, molestiae blanditiis adipisci repellendus velit quasi ullam et? </li> </ul> </div> </td> </tr> </table> </div> </div>';
var swordsContent='<div id="app"> <div class="swords"> <table class="elements"> <th colspan="2">Pro-Bending</th> <tr> <td class="elem-describe" rowspan="3"> <div> <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae vero molestiae dolor praesentium facilis quibusdam repellendus consectetur excepturi maxime, minus, quam, suscipit distinctio atque delectus magnam eveniet est quas fugit! <br> Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sapiente nihil mollitia asperiores voluptas voluptatum sequi magnam, sint tempore saepe dolore earum ut cum aliquid reprehenderit et possimus repellendus laudantium hic. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi officiis ipsa facere nobis veritatis esse quos nam neque, tempora, sit culpa aperiam nihil quisquam repudiandae corrupti expedita voluptatem. Porro, consequatur. <br> Nulla quia obcaecati modi maiores earum nam quos nobis? Suscipit quas nesciunt illo praesentium adipisci libero doloremque delectus excepturi optio corrupti non sint porro alias ducimus, at fugiat quidem? Possimus. <br>Odit suscipit sint esse nam laboriosam ex quis laborum nihil aliquam doloribus similique sequi consectetur, doloremque reprehenderit minima placeat nulla nesciunt velit! Alias excepturi similique iure hic beatae repellat architecto.</p> </div> </td> <td class="elem-describe" style="height: 50px;"> <div class="title"> <!-- Chinese --> <h1>Pledged Platoon</h1> <ul> <li>Jifeng</li> <li>Jampa</li> </ul> </div> </td> </tr> <tr> <td class="elem-describe" rowspan="2"> <div class="elem-describe"> <h1>Element Mutations</h1> <ul> <li>Adipisicing deserunt eum!</li> <li>Lorem, ipsum dolor sit amet consectetur adipisicing elit.</li> <li>Unde pariatur facere dignissimos aut soluta mollitia eveniet eligendi dolores praesentium voluptates ullam veniam reprehenderit, doloribus recusandae accusamus!</li> <li>Lorem ipsum dolor sit amet consectetur adipisicing elit. Est ex libero harum fuga!</li> <li>Ducimus odit laboriosam quia, molestiae blanditiis adipisci repellendus velit quasi ullam et? </li> </ul> </div> </td> </tr> </table> </div> </div>';
var wandsContent='<div id="app"> <div class="wands"> <table class="elements"> <th colspan="2">Pro-Bending</th> <tr> <td class="elem-describe" rowspan="3"> <div> <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae vero molestiae dolor praesentium facilis quibusdam repellendus consectetur excepturi maxime, minus, quam, suscipit distinctio atque delectus magnam eveniet est quas fugit! <br> Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sapiente nihil mollitia asperiores voluptas voluptatum sequi magnam, sint tempore saepe dolore earum ut cum aliquid reprehenderit et possimus repellendus laudantium hic. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi officiis ipsa facere nobis veritatis esse quos nam neque, tempora, sit culpa aperiam nihil quisquam repudiandae corrupti expedita voluptatem. Porro, consequatur. <br> Nulla quia obcaecati modi maiores earum nam quos nobis? Suscipit quas nesciunt illo praesentium adipisci libero doloremque delectus excepturi optio corrupti non sint porro alias ducimus, at fugiat quidem? Possimus. <br>Odit suscipit sint esse nam laboriosam ex quis laborum nihil aliquam doloribus similique sequi consectetur, doloremque reprehenderit minima placeat nulla nesciunt velit! Alias excepturi similique iure hic beatae repellat architecto.</p> </div> </td> <td class="elem-describe" style="height: 50px;"> <div class="title"> <!-- Japanese --> <h1>Fierce Mages</h1> <ul> <li>Daitan</li> <li>Achak</li></ul> </div> </td> </tr> <tr> <td class="elem-describe" rowspan="2"> <div class="elem-describe"> <h1>Element Mutations</h1> <ul> <li>Adipisicing deserunt eum!</li> <li>Lorem, ipsum dolor sit amet consectetur adipisicing elit.</li> <li>Unde pariatur facere dignissimos aut soluta mollitia eveniet eligendi dolores praesentium voluptates ullam veniam reprehenderit, doloribus recusandae accusamus!</li> <li>Lorem ipsum dolor sit amet consectetur adipisicing elit. Est ex libero harum fuga!</li> <li>Ducimus odit laboriosam quia, molestiae blanditiis adipisci repellendus velit quasi ullam et? </li> </ul> </div> </td> </tr> </table> </div> </div>';

function init(){
    
    $("nav a").click(function (e) {
        let btnId = this.id;
        let contentId = btnId + "Content";



        console.log("clicked " + btnId);
        console.log(contentId);
        console.log(cupsContent);
        $("#app").html(eval(contentId));
        //$("#app").append(btnId);
        //$("#app").prepend(btnId);
        elemButtonListener();
    });

   
    // console.log("thar be a draft " + userName);
}

function elemButtonListener(){
    $(".elements a").click(function (e) {
        let btnId = this.id;
        let contentId = btnId + "Content";

        console.log("clicked " + btnId);
        console.log(contentId);
        console.log(cupsContent);
        $("#app").html(eval(contentId));
        //$("#app").append(btnId);
        //$("#app").prepend(btnId);
    });
}
//this checks for all Elements in the browser
$(document).ready(function(){
    elemButtonListener();
    init();
});